spring.application.name=ai-image-app
server.port=${PORT:9090}
server.servlet.context-path=/

# Hugging Face Configuration
HF_TOKEN=${HF_TOKEN:}
HF_MODEL_URL=${HF_MODEL_URL:}

# Gemini API Configuration
GEMINI_API_KEY=${GEMINI_API_KEY:}

