spring.application.name=ai-image-app
server.port=${PORT:9090}
server.servlet.context-path=/
HF_TOKEN=${HF_TOKEN:}
HF_MODEL_URL=https://router.huggingface.co/hf-inference/models/black-forest-labs/FLUX.1-schnell